[workspace]
resolver = "2"

members = [
#    "common",
    "pallets/ares-oracle",
    "pallets/oracle-finance",
    "pallets/staking-extend",
    "pallets/member-extend",
    "pallets/challenge",
    "pallets/collective",
    "pallets/price-estimates",
    "pallets/session",
    "pallets/session/benchmarking",
]

#[patch."https://github.com/paritytech/substrate"]
#pallet-session ={path = "./pallets/session" }
#pallet-session-benchmarking ={path = "./pallets/session/benchmarking" }
