[workspace]
resolver = "2"

members = [
    "pallets/pallet-ocw",
    "pallets/ocw-finance",
    "pallets/staking-extend",
    "pallets/member-extend",
    "pallets/challenge",
    "pallets/collective",
    "pallets/price-estimates"
]
